"use client";

import { motion } from "framer-motion";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { ArrowRight, Sparkles, Zap, Share2 } from "lucide-react";

export default function Home() {
  return (
    <div className="flex flex-col items-center justify-center">
      {/* Hero Section */}
      <section className="relative w-full overflow-hidden py-24 md:py-32 lg:py-40">
        <div className="container px-4 md:px-6 relative z-10 mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="mx-auto max-w-3xl space-y-6"
          >
            <div className="inline-flex items-center rounded-full border border-white/10 bg-white/5 px-3 py-1 text-sm text-primary backdrop-blur-xl">
              <span className="flex h-2 w-2 rounded-full bg-green-500 mr-2 animate-pulse"></span>
              The ultimate prompt library
            </div>
            <h1 className="text-4xl font-extrabold tracking-tight sm:text-5xl md:text-6xl lg:text-7xl bg-clip-text text-transparent bg-gradient-to-b from-white to-gray-500">
              Unleash Your <br className="hidden sm:inline" />
              <span className="text-primary">AI Creativity</span>
            </h1>
            <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl">
              Discover, share, and remix the best AI prompts. Join a community
              of creators and push the boundaries of what's possible with AI
              art.
            </p>
            <div className="flex flex-col gap-4 sm:flex-row sm:justify-center">
              <Link href="/discover">
                <Button
                  size="lg"
                  className="h-12 w-full sm:w-auto px-8 gap-2 text-lg"
                >
                  Explore Prompts
                  <ArrowRight className="h-4 w-4" />
                </Button>
              </Link>
              <Link href="/prompts/create">
                <Button
                  variant="outline"
                  size="lg"
                  className="h-12 w-full sm:w-auto px-8 text-lg"
                >
                  Create New
                </Button>
              </Link>
            </div>
          </motion.div>
        </div>

        {/* Background Gradients */}
        <div className="absolute top-1/2 left-1/2 -z-10 h-[500px] w-[500px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-primary/20 blur-[100px] opacity-50"></div>
      </section>

      {/* Features Section */}
      <section className="w-full py-12 md:py-24 lg:py-32 bg-white/5 border-y border-white/5">
        <div className="container px-4 md:px-6 mx-auto">
          <div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-3">
            <FeatureCard
              icon={Sparkles}
              title="Inspiration"
              description="Browse thousands of creative prompts generated by the community."
            />
            <FeatureCard
              icon={Share2}
              title="Share & Collaborate"
              description="Showcase your best work and get feedback from other AI enthusiasts."
            />
            <FeatureCard
              icon={Zap}
              title="Instant Remix"
              description="One-click to copy prompts and try them on your favorite models."
            />
          </div>
        </div>
      </section>
    </div>
  );
}

function FeatureCard({ icon: Icon, title, description }) {
  return (
    <motion.div
      whileHover={{ y: -5 }}
      className="flex flex-col items-center space-y-4 rounded-xl border border-white/10 bg-white/5 p-8 text-center transition-colors hover:border-primary/50"
    >
      <div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary/10 text-primary">
        <Icon className="h-6 w-6" />
      </div>
      <h3 className="text-xl font-bold">{title}</h3>
      <p className="text-muted-foreground">{description}</p>
    </motion.div>
  );
}
